### Get job programs
GET http://localhost:3000/api/jobPrograms?filter=test
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Get job program definition
GET http://localhost:3000/api/jobPrograms/testJobProgram
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Get job with a filter
GET http://localhost:3000/api/jobs
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Get job
GET http://localhost:3000/api/jobs/testSpecTimeJob1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Create a job
POST http://localhost:3000/api/jobs
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "testSpecTimeJob2",
  "description": "specific time job",
  "identity": {
    "id": "DH001"
  },
  "steps": [
    {
      "program": "testJobProgram",
      "parameters": {
        "param1": "value1"
      }
    }
  ],
  "startCondition": {
    "mode": 1,
    "specificTime": "2021/02/20 12:00:00"
  },
  "outputSetting": {
    "console2ApplicationLog": true
  }
}

### Schedule a job
POST http://localhost:3000/api/jobs/schedule
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

[
  "testSpecTimeJob",
  "testSpecTimeJob1"
]

### Get job occurrences
GET http://localhost:3000/api/jobs/testSpecTimeJob1/occurrences
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
